### ISSUE TITLE
[BUG] The ExplytSpringBoot settings lead to the incorrect direction

### ISSUE THREAD

**Issue by Evgenia-enough** [explyt/spring-plugin#13]
### Component

ExplytSpringBoot panel

### Problem details

![image](https://github.com/user-attachments/assets/e0c227de-50bc-45c3-9963-3c6797316548)
![image](https://github.com/user-attachments/assets/c831702b-3c1e-4978-acb7-c208c77e1851)

### Steps to reproduce

1. Open ExplytSpringBoot panel
2. Click on settings button
3. Click ExplytSpringBoot settings... menu option
4. Last visited page in Setting window is opened

Expected result: 
* Tools -> Explyt Spring configuration page in Settings should be opened.  

### Plugin version

243.1.2801

### Build system

IntelliJ

**Comment by imuromtsev** [comment]
fixed in dev build

**Comment by imuromtsev** [comment]
fixed
