### ISSUE TITLE
[BUG] The classpath is not correctly defined before the property file in the @TestPropertySource annotation.

### ISSUE THREAD

**Issue by denmaltsev** [explyt/spring-plugin#15]
### Component

Inspection

### Problem details

The properties file exists and the correct path is indicated in the prompt.
![Снимок экрана 2024-12-24 в 14 40 42](https://github.com/user-attachments/assets/6361a448-8b8e-4249-8604-f2e77722cc05)

### Plugin version

243.1.2927

### Build system

Maven

**Comment by denmaltsev** [comment]
When trying to fix a file, it is created in the root of the java folder.
![Снимок экрана 2024-12-24 в 14 46 57](https://github.com/user-attachments/assets/502b3389-4fc1-49b3-a5f9-fd83fce1c180)

**Comment by imuromtsev** [comment]
fixed
